### ISSUE TITLE
As a potential member, I want to be able to pay with paypal so I can become a paid member

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#10]
I should be able to buy using the paypal option, my sale should go through. The money go into the account,

Talk to claire for account information.

The database should be updated within 2 minutes for paymentStatus to be PAID.

**Comment by Doddzy** [comment]
Ready for testing =D

**Comment by Doddzy** [comment]
Asked to see if security person can take a look at it

**Comment by rdoh** [comment]
waiting on Frenchie to let us know if any PayPal issues
