### ISSUE TITLE
As a pirate party secretary, I want to view a list of members

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#11]
phase 1: list of members (includes audited flag), admin authentication, export of list

aec roles check - auditor only sees non-audited members

Must log all access to members in database

**Comment by akjones** [comment]
Credit card: features basically done, but finish the UI. Get npm install to work. Test has been added for payment, should be done once Claire commits and merges with Issy.

**Comment by fleur94** [comment]
Mockup for secretary view - as discussed, it's basically just a table with flags for verified or unverified. Feedback? 

![member list - desktop](https://cloud.githubusercontent.com/assets/16026868/12435009/a6299d42-bf5e-11e5-95d5-c5b68c377d21.png)

**Comment by fleur94** [comment]
Updated with links to full member details page:

![member list - desktop](https://cloud.githubusercontent.com/assets/16026868/12436918/6d5a0f56-bf6d-11e5-98c4-c80dd108684c.png)

**Comment by akjones** [comment]
add links and stuff to members

**Comment by akjones** [comment]
still need:
- route to be enabled (with passportjs authentication based on local strategy - already configured)
- 2-factor auth to be set up
- login route/handler
- logout route/handler
- front-end
- controller should return links for each member

done:
- basic passportjs auth with local strategy
- adminController has a route membersList which generates the necessary data

**Comment by rdoh** [comment]
The admin interface should be generic, ie unbranded -- for other groups to use without needing to rebrand

**Comment by rdoh** [comment]
should include acceptance tests
