### ISSUE TITLE
As a potential member, I want to be able to register my details so I can become a member

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#3]
Should cover basic membership details for the core membership system (pirate party specific stuff will come later)

Acceptance Criteria:
- When I submit the form, my details should be persisted in the database
- Since the form is generic, the membership details should include: email, name, address, date of birth, phone number
- When I submit the form, a member-sign-up event should be logged
- I should be able to register on my phone
- When I submit the form, the data should be sanitised

Deployment info:
- Prod will be a server TBD
- Pre-prod will be on heroku
- ci will probably be snap-ci

**Comment by akjones** [comment]
i've just rolled #25 back into this card

**Comment by akjones** [comment]
Don't forget logging!

**Comment by akjones** [comment]
a member looks like this:

{
    "firstName": "Sherlock",
    "lastName": "Halmes",
    "email": "sherlock@halmes.co.uk22",
    "dateOfBirth": "22 December 1900",
    "phoneNumber": "0396291146",
    "residentialAddress": {
        "address": "222b Baker St",
        "suburb": "London",
        "country": "England",
        "state": "VIC",
        "postcode": "1234"
    },
    "postalAddress": {
        "address": "303 collins st",
        "suburb": "melbourne",
        "country": "australia",
        "state": "VIC",
        "postcode": "3000"
    }
}

**Comment by Doddzy** [comment]
Also need to add an optional gender field and optional secondary phone number to DB. Postcode needs to be changed from int to String in DB as they range from 0200-9999

^ removed, completed in #26 instead

**Comment by akjones** [comment]
our api looks like this:

GET /members/new  - gives us the form (which js will paginate)
POST /members - expects a member and will save it to the db, should redirect to some kind of thanks page on success, redirect back to /members/new on server error

**Comment by fleur94** [comment]
General comments:
- In the postal address section, the "address" label is below everything else, should go above the first input.
- Something that was picked up in user testing: remove stars from compulsory labels, and include (optional) next to the optional fields.

I have other comments, but they relate to other cards so I'll put them there. Good job!

**Comment by akjones** [comment]
the log message when a member signs up looks like this: 

info:  firstName=Dr, lastName=Bones, email=akjones+test1@thoughworks.com, gender=Frog, primaryPhoneNumber=0400000000, secondaryPhoneNumber=undefined, dateOfBirth=15/11/1945, address=303 Collins St, suburb=Melbourne, postcode=3000, state=VIC, country=Australia, $ref=$["residentialAddress"]

i'd like to know what sort of event i'm seeing

**Comment by akjones** [comment]
also the 3 letter state code is not obvious on the form - could we use a dropdown to avoid validation issues (we can hardcode it to australia for now)?
