### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#33]
- Make asterisks red - DONE
- Add hover styles - DONE
- Fix spacing - DONE
- Make “whatever you want" bold - DONE
- Style declaration checkbox - DONE
- Restyle payment contribution box  - DONE
- Fix mobile styles - DONE
- Add "(optional)" in italics next to optional fields. - DONE
- Note that the progress bar has changed slightly since the original design: text and circles are smaller to reduce vertical space at the top. Also, the text in the progress bar is a bit de-centred at the moment. - DONE
- Add ticks. - DONE
- Style modal. - DONE
- Replace Stripe image. -DONE
- Change position of payment messages. - DONE
- Red label and border for payment contribution validation. - DONE
- Make text for error and info boxes smaller. - DONE

**Comment by fleur94** [comment]
Here is the updated svg logo, to be replaced in the current version: https://thoughtworks.box.com/s/it6s15yfzxffhmmtae9zqod60ybs5raa

The only difference is that I have converted the text into outlines, so that the font is retained.

**Comment by akjones** [comment]
mobile layout needs tweaking - it is usable, just needs some alignment & spacing work.
