### ISSUE TITLE
Rethink the eligibility screen

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#35]
Users did not respond well to it in user testing and also the current statements do not cater for all scenarios.

**Comment by fleur94** [comment]
Re-thought the eligibility screen - basically users have to answer three questions and get given the membership type that they qualify for.

Claire suggested renaming this stage to "Membership Type" because eligibility sounds like something the user might pass or fail. 

![membership type](https://cloud.githubusercontent.com/assets/16026868/12340890/dbd62fc8-bb71-11e5-9fe6-f37d99ce88df.png)

After the user clicks the button above, they get the result on the same page as per below.

![membership type - with answers](https://cloud.githubusercontent.com/assets/16026868/12340897/e6a2062a-bb71-11e5-8acb-3ce5aaae8704.png)

**Comment by bbqsrc** [comment]
Very nice.
