### ISSUE TITLE
Integrate new design in the front-end (so far, Chris has added the confirm page)

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#42]
Acceptance Criteria:

Given an user on the Confirm page
When checks the confirmation box
And clicks the continue button
Then the user can go to the payment page

Given an user on the Confirm page
When the user does not check the confirmation box
And clicks the 'Continue' button
Then the user remain on the Confirm page

Given an user checked the details on the Confirm page
When the user clicks ‘go back’ button
Then the user returns to the Details page 

Given an user clicks 'go back' button on the Confirm page
When goes back to the Details page
Then the user's information is remain

**Comment by orangehb** [comment]
Acceptance Criteria:

Given an user on the Confirm Page
When checks the confirmation box
And clicks the continue button
Then the user can go to the payment page

Given an user on the Confirm page
When the user does not check the confirmation box
And clicks the 'Continue' button
Then the user remain on the Confirm Page

Given an user checked the details on the Confirm Page
When the user clicks ‘go back’ button
Then the user returns to the Details Page

**Comment by fleur94** [comment]
^ And if the user goes back to the details page, their information still needs to be there.

**Comment by orangehb** [comment]
Added! thanks Florencia.

**Comment by Doddzy** [comment]
Ready for testing
