### ISSUE TITLE
Intergrate with postgres

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#5]

**Comment by bbqsrc** [comment]
I thought the project was going to use PostgreSQL?

**Comment by akjones** [comment]
Yeah, i think pgsql at this stage. i still need to tinker with the cards a bit.

**Comment by fleur94** [comment]
Ah sorry, the tender said MongoDB so I must have gotten confused :)

**Comment by bbqsrc** [comment]
:+1:
