### ISSUE TITLE
Add payment status to invoice

### ISSUE THREAD

**Issue by Doddzy** [ppau/project-m#50]
Add Reference number:
- Reference number need to represent the membership type for user pay by cheque or direct deposit. e.g. F1(Full membership with user id 1)
- Reference number remain the transaction id for user pay be credit card or paypal.

**Comment by akjones** [comment]
i also noticed that there doesn't seem to be a payment reference for direct deposit or cheque set when those invoices get created - what's happening with that?

**Comment by issy-li** [comment]
Invoice reference solved :)

**Comment by akjones** [comment]
ready for testing, akjones to test.

**Comment by akjones** [comment]
the invoice subsystem needs some improvements:
- reference number should be generated inside the invoice service CHECKED
- reference number should be comprised of membership type + invoice id CHECKED
- reference number should be set on creation of all invoices CHECKED
- add a transaction id to store 3rd party transaction references CHECKED
- charge card logic should live in the invoice service CHECKED
- inside the invoice service, createNewInvoice and createEmptyInvoice are duplicates CHECKED
- the "create" and "newinvoice" terms are overloaded in the invoice service - these should be updated to reflect their actual function CHECKED
- code format in invoice service needs work CHECKED
- we need to be careful of exposing db errors to users (in invoicescontroller) CHECKED
- invoices should be properly associated with members in the db (with a foreign key constraint) CHECKED
- other general refactoring (eg using named functions in promise chains - like memberService) CHECKED

**Comment by akjones** [comment]
payment status should probably have a default value in the db - it'll simplify logic in the app

**Comment by issy-li** [comment]
Issy finished the refactoring, and now the server will response with different http code and error messages(400  for stripe failure, 500 for other server errors).
