### ISSUE TITLE
Membership type explanation modal

### ISSUE THREAD

**Issue by Doddzy** [ppau/project-m#56]
Acceptance Criteria:

Given an Australian citizen enrolled to vote in Australia 
When selected 'Yes'  to 'Are you a member of another Australian political party'
And click the "What are the different membership types?" link on the supporter membership info box
Then the user can view  the explanation modal with four types of Membership details

Given an Australian citizen enrolled to vote in Australia 
When selected 'No'  to 'Are you a member of another Australian political party'
And click the "What are the different membership types?" link on the full membership info box
Then the user can view  the explanation modal with four types of Membership details

Given an user have Permanent Resident Visa not enrolled to vote in Australia 
When selected 'Yes'  to 'Are you a member of another Australian political party'
And click the "What are the different membership types?" link on the supporter membership info box
Then the user can view  the explanation modal with four types of Membership details

Given an user have Permanent Resident Visa not enrolled to vote in Australia 
When selected 'No'  to 'Are you a member of another Australian political party'
And click the "What are the different membership types?" link on the Permanent Resident membership info box
Then the user can view  the explanation modal with four types of Membership details

Given an user international citizen or have a Temporary visa not enrolled to vote in Australia 
When selected 'Yes'  to 'Are you a member of another Australian political party'
And click the "What are the different membership types?" link on the International membership info box
Then the user can view  the explanation modal with four types of Membership details

Given an user international citizen or have a Temporary visa not enrolled to vote in Australia 
When selected 'No'  to 'Are you a member of another Australian political party'
And click the "What are the different membership types?" link on the International membership info box
Then the user can view  the explanation modal with four types of Membership details

**Comment by fleur94** [comment]
Ready for testing.
