### ISSUE TITLE
As a pirate party member, I want to be able to renew my membership.

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#6]
To edit the info, people include their last name & date of birth - after which they can see the pre-filled form.

**Comment by fleur94** [comment]
User flow:
- Member gets reminder email to verify their membership and clicks on the link.
- Gets redirected to the below. We will later implement the update membership feature, which basically will consist in having a link next to the button saying "or update your details". This link will take the user to the details page, but it's another story entirely. 
  ![renew membership](https://cloud.githubusercontent.com/assets/16026868/12739890/c97f9f0e-c9c1-11e5-92e3-4324a5973d66.png)
- Next page is contribution:
  ![contribution](https://cloud.githubusercontent.com/assets/16026868/12739921/29abeed2-c9c2-11e5-944b-ad4783bc6d85.png)
- And finally, thank you:
  ![thank you](https://cloud.githubusercontent.com/assets/16026868/12739960/88d0aa4c-c9c2-11e5-80eb-a71e46ffaf93.png)

**Comment by natyoung** [comment]
Delete the renewal hash after the renewal date is set

**Comment by Doddzy** [comment]
XMLHttpRequest in renew.jsx should be async
