### ISSUE TITLE
As a potential member, I want to register to become a member of pirate party with different membership types available to me.

### ISSUE THREAD

**Issue by fleur94** [ppau/project-m#7]
Scope of this card - fully polished user flow for full member registration.

Example criteria of 1 of the 4 options (Full, supporter, Permanent Resident, international)

Acceptance Criteria:

Given an user in the Membership Type page
When check the Permanent Resident box
Then the user can view  'You are eligible for a Permanent Resident Membership' information in the iFrame

Given an user select Permanent Resident Type
When in the Details page
Then the user can see the correct subheadings and the references to voting 
And the labels and inputs will remain the same

Given an user select Permanent Resident Type
When in the Confirm page
Then the user can see the correct declaration text
And the "Check your details" part remains the same

**Comment by bbqsrc** [comment]
Relevant documentation:

Constitution: [Section 4 - Membership](https://pirateparty.org.au/constitution/#4)
By-law: [2015-01 - Additional Membership Types](https://pirateparty.org.au/wiki/By-laws#By-law_2015-01_-_Additional_membership_types)

**Comment by fleur94** [comment]
For guidance, refer to the design prototype for the complete Full Member flow (it does not include validation errors): https://projects.invisionapp.com/share/A75JY6OEG#

**Comment by fleur94** [comment]
![membership type](https://cloud.githubusercontent.com/assets/16026868/12465974/257456a2-c025-11e5-8792-57414ec1b033.png)

![membership type - with answers](https://cloud.githubusercontent.com/assets/16026868/12465992/456dac60-c025-11e5-8b31-997a16e0c309.png)

**Comment by Doddzy** [comment]
Validation message atm when not all selected "Please answer all the questions"

**Comment by Doddzy** [comment]
Validation message atm when not all selected "Please answer all the questions"

**Comment by fleur94** [comment]
![pay what you want](https://cloud.githubusercontent.com/assets/16026868/12467687/97cab6fe-c031-11e5-8d46-e86b50d3a9cb.png)

**Comment by Doddzy** [comment]
Ready for testing, also includes: All membership types on first page, altered text on details page, namely missing references to AEC when not full member and confirm details page also has altered text when not full member.

Eligibility page should also display errors when invalid combinations of radio buttons clicked and not allow transitioning.

**Comment by pameck** [comment]
Things I've found: 
- Typo: You are entitled to a International Membership. -->  an International Membership

**Comment by pameck** [comment]
- "What are the different membership types" link points to a doc instead of a page as shown in the prototype, but I'm not sure if that's part of this story.
