### ISSUE TITLE
Fix Math.random in acceptance tests to be more... random

### ISSUE THREAD

**Issue by Doddzy** [ppau/project-m#79]
In the user signup test, since email has to be unique, there is a math.random() changing the email, this will sometimes fail if it collides with existing user, find a solution to this.

**Comment by aewens** [comment]
``` javascript
require('crypto').randomBytes(48, function(ex, buf) {
  var token = buf.toString('hex');
});
```

or 

``` javascript
var token = crypto.randomBytes(64).toString('hex');
```

Would either of these solve your problem?
